imports:
  - { resource: sifodyas.parameters.yml, ignore_errors: true }
#   - { resource: 'http://mellisuge/app_dev.php/api/public/sifodyasConfig', type: 'json' }

#app:
#  waza: %kernel.name%/fddf
#  depper:
#    anddepper:
#      andagain: '%kernel.name%'
#      other: '%sub.mmm.eeee%'
#  test: '%cwcxwcwx[0]%'
#  fdp:
#    - aze
#    - qsd
#    - djfjfjgj
#    - '%kernel.name%'
#    - '%sub.mmm.eeee%'
#  wesh: ça va ?

parameters:
  env(TOTO): "test%kernel.path%"
  # env(foo): "%kernel.name%"
  # env(bar): "%kernel.bundles%"
  # env(baz): "%kernel.coreBundles%"
  BAR: "%env(resolve:TOTO)% quelquechose"
  ZOZ: "sisisiisis  %env(toto)% AZAZ"
app:
  # foo: "%env(resolve:TOTO)% etc hello"
  baz: 'normal %env(toto)%'
  qux: 'wesh => %env(resolve:toto)% BIZArrez'

